### ISSUE TITLE
Updated upstream builds of Tor-Server, working and tested.

### ISSUE THREAD

**Issue by chriswayg** [DarkIsDude/tor-server#5]
Hi DarkIsDude nice to see, that you updated my previous version to be functional again! The more Tor servers the better!

I updated my Tor-Server to Debian 9 stretch, which will auto-update on Docker Hub more reliably (as it is not built from source), but is using the Tor repositories with recent builds. You may want to incorporate some of my changes into your version:

- This image can be run as an obfuscated Tor bridge for people under persecution
- Instructions have been updated and improved
- Easy to run with IPv6 enabled 
- Added automated Travis testing

https://hub.docker.com/r/chriswayg/tor-server/

**Comment by DarkIsDude** [comment]
Thanks @chriswayg , I go back to your repo!

**Comment by hydrosam** [comment]
Hey it seems like the version is getting stuck at Tor 0.4.2.7 but the 0.4.2.x is out of support so there seem to be intermittent issues. Any ideas on how to update the docker so that the relays built on it move along to newer versions?

**Comment by DarkIsDude** [comment]
@hydrosam thanks for pinging me. Feel free to open a new issue when you want.

I just rerun the pipeline to build it, I'm now using 0.4.4.5. So you just need to pull the image and you'll use the new version

**Comment by Moppen72** [comment]
Mar 20 04:05:06.000 [warn] Please upgrade! This version of Tor (0.4.7.13) is obsolete, according to the directory authorities. Recommended versions are: 0.4.8.1-alpha,0.4.8.2-alpha,0.4.8.3-rc,0.4.8.4,0.4.8.5,0.4.8.6,0.4.8.7,0.4.8.8,0.4.8.9,0.4.8.10

**Comment by DarkIsDude** [comment]
@Moppen72 done 🙏 

```
Mar 20 13:38:48.066 [notice] Tor 0.4.8.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1w, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.4.8 and Glibc 2.31 as libc
```

**Comment by Moppen72** [comment]
Thanks, that was quick.
But after the Update, the container doesn't work anymore:
Log:
`[FATAL tini (7)] exec docker-entrypoint failed: Exec format error`

**Comment by DarkIsDude** [comment]
oO ! What is your command to start it ? And or the config to be able to reproduce it ?

**Comment by Moppen72** [comment]
Oh, there is a warning:

```
docker create
  --name='tor-relay'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="xxxxxx"
  -e HOST_CONTAINERNAME="tor-relay"
  -e 'TOR_NICKNAME'='xxxxxxxx'
  -e 'CONTACT_EMAIL'=xxxxxxxxxxxxxx@mailbox.org'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://clipartart.com/images/tor-browser-icon-clipart-9.png'
  -p '9030:9030/tcp'
  -p '9001:9001/tcp'
  -v '/etc/localtime':'/etc/localtime':'rw'
  -v '/mnt/user/appdata/tor-relay/':'/etc/tor/':'ro'
  --init 'doudou34/tor-server'

WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v2) and no specific platform was requested
a3aec22bca9ec65de1be499f2bca74a0e143b66fd51820b4080dfc963153dae0

The command finished successfully!
```

**Comment by DarkIsDude** [comment]
```
docker create \
  --name='tor-relay' \
  --net='bridge' \
  -e TZ="Europe/Berlin" \
  -e HOST_OS="Unraid" \
  -e HOST_HOSTNAME="xxxxxx" \
  -e HOST_CONTAINERNAME="tor-relay" \
  -p '9030:9030/tcp' \
  -p '9001:9001/tcp' \
  --init 'doudou34/tor-server'
```

This is running here. I'm on Apple silicon, what's yours ? Are you using an intel or amd64 ?

**Comment by DarkIsDude** [comment]
Ok indeed I think it's fixed. Discovered the multi build image tonight. The new command to build and run : `docker build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8 --push --no-cache -t doudou34/tor-server:latest .`. Should work now ? Which architecture do you use ? @Moppen72

**Comment by Moppen72** [comment]
Very well done, sir. My Tor Relay is back up and running. Your Support is exemplary.

I am running a unRaid-Server on linux/amd64/v2, I guess. If you need, I can provide further Information about my System.

**Comment by DarkIsDude** [comment]
BTW I just pushed a new tag : `0.4.8.10`. I'll maybe try to push with more tags to avoid always pushing only latest and keep some history 🙏
