### ISSUE TITLE
Tor is on an obsolete version!

### ISSUE THREAD

**Issue by mariaa144** [DarkIsDude/tor-server#8]
Debian bullseye has an obsolete version of Tor packaged now it seems. Consider updating the Docker image to include a current version of Tor.

I have an update container based on your Docker Hub image and it is running Tor 0.4.5.10.

**Comment by DarkIsDude** [comment]
@mariaa144 upgraded to the latest version. Thanks for the ping.

Can you confirm ?

```
Mar 19 20:09:15.885 [notice] Tor 0.4.7.13 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.4.8 and Glibc 2.31 as libc.
```

**Comment by mariaa144** [comment]
All good! Thank you! ✌️
